name: CMake (Windows)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install CUDA Toolkit 12.1
      uses: Jimver/cuda-toolkit@v0.2.21
      with:
        cuda: '12.1.0'

    - name: Bootstrap vcpkg
      shell: pwsh
      run: |
        cd external/vcpkg
        git fetch --unshallow
        ./bootstrap-vcpkg.bat

    - name: Configure CMake
      shell: pwsh
      run: |
        cmake -S . -B build `
          -DCMAKE_TOOLCHAIN_FILE="external/vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DVCPKG_TARGET_TRIPLET=x64-windows `
          -DENABLE_CUDA=ON `
          -DCMAKE_CUDA_FLAGS="-allow-unsupported-compiler"

    - name: Build
      shell: pwsh
      run: cmake --build build --config ${{ env.BUILD_TYPE }} -j 1

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: alien-windows-x64-complete
        path: |
          build/${{ env.BUILD_TYPE }}/*.exe
          build/${{ env.BUILD_TYPE }}/*.dll
          build/vcpkg_installed/x64-windows/bin/*.dll
